### ISSUE TITLE
Not identifying jewels

### ISSUE THREAD

**Issue by ixrogue** [kolton/d2bot-with-kolbot#1337]
Ive used other people’s pickits for jewels and it seems that it will pick up the facets/magic/rare jewels and stashing without identifying. 
Could someone give me an example of how a correct line code will pick up a certain stat jewel compared to just stashing an Non-identified  jewel? 

Also, does Kolton nip file (for jewels) identify before stashing correct stats on jewel?

I never realize how many jewels gets picked up in a single run...

**Comment by DarkHorseDre** [comment]
just check the jewel section of the original kolton.nip file?
https://github.com/kolton/d2bot-with-kolbot/tree/master/d2bs/kolbot/pickit

First jewel entry is:
[Name] == jewel && [quality] == magic # ([enhanceddamage] >= 40 || [tohit] == 100 || [maxdamage] >= 15) && ([maxhp] == 20 || [ias] >= 15 || [itemreqpercent] <= -15 || [strength] >= 9 || [dexterity] >= 9)

It has to ID the item in order to read and check the stats.

**Comment by Blitz28** [comment]
from my understanding after making a pickit from scratch multiple times is that the # in the line is the identifying command. However there needs to be a stat after the # for the pickit to check so a # by itself wont identify items.

an example:
[name] == jewel && [quality] <= rare # [dexterity] >= 5

^^ this will cause your pickit to grab rare and magic  jewels and identify them to see if they have 5 or more dexterity point on them (just an example, i wouldnt use this line, look for rarer stats)

unid example:
[name] == jewel && [quality] == rare 
or
[name] == jewel && [quality] == rare # 

^^ this will cause you pickit to collect rare jewels but not identify them

**Comment by ixrogue** [comment]
What you said about the " # " being the identifier has made a huge clarity boost for me and future others. thank you
