### ISSUE TITLE
opening and crashing continuously.

### ISSUE THREAD

**Issue by HeyArnold33** [kolton/d2bot-with-kolbot#2139]
I have had kolbot running in the past and it has worked great. I decided to get a 4th account. Since trying to get that one running all of my profiles stopped working. 
I press start and the Diablo game opens but immediately closes and it does this over and over and over again. I've tried reinstalling everything but I just cant seem to get it to work. They all have different CD keys and game paths. Also when I try to run 2 of them at a time it says that only one copy of Diablo can run but I have them on different game paths to different downloads of the game.
Help a brother out please.
![kolbot](https://user-images.githubusercontent.com/41846446/72133231-27fb7000-333e-11ea-96e4-5d6e62860382.jpg)

**Comment by Fa-b** [comment]
Was working when there was only 3 installations?
How did you install the fourth copy?
Is at least one of the profiles starting properly (try to stop 3 profiles and run only 1)?
Are you 100% certain the game paths are different?

Check if you have some entries for Game.exe in your environment variables. I don't know if kolbot would care about that, it's just a guess. If it did, maybe your fourth installation added one installation to your PATH and now ALL profiles try to access the same Game.exe because of that.
If that doesn't help, maybe I can find a way to print the attempted path to the console in order to debug this issue further.

**Comment by HeyArnold33** [comment]
First off I do have to apologize I am a newb when it comes to coding and figuring this stuff out as you can tell by my profile. 
So I kept on looking and I think it did have something to do with the Game.exe. When I tried to open each of the game installations by itself and not through kolbot, there was a error message about the Game.exe. When I closed out of the error message it then fired out another message saying that it was fixed by some auto detection thing. I then opened each of the games and downloaded the automatic patch. Now they are all working together just fine on kolbot. 👍 
Do you have any idea what happened? Or what I did to make it work? Like I said I'm kinda new to all of this, just trying to get more educated on it.

**Comment by Fa-b** [comment]
Sounds like you had the latest patch missing... confused about why it was working before that with only three copies though. No idea, just started playing again about 5 days again after ~10years of a break :D

**Comment by HeyArnold33** [comment]
Nice! Well, welcome back! Thanks for your help as well!
