### ISSUE TITLE
Crafting amulets

### ISSUE THREAD

**Issue by aochalkov** [kolton/d2bot-with-kolbot#2161]
Hello, need help.
I enabled crafting amulets, but seems bot can't find proper amulets base (high lvl). But my char is 94 level, so she can buy it (gamble). How can I enable gambling to complete recipe?
I added all other mats in pick it list, so bot has all items except amu and don't craft :(

**Comment by InterestingIndeed** [comment]
Gambling can be activated and setup in the character configuration (kolbot/libs/config/YourCharacter.js), the gambling part starts at line 334. Set Config.Gamble to true, set a gold amount on where to start gambling, set a gold amount on where to stop gambling. Further down, you can chose which item(s) to gamble for. The code down below should do what you want to have. I recommend changing the lines in the config manually, to see what you are doing.


`	// Gambling config
	Config.Gamble = true;
	Config.GambleGoldStart = 1000000;
	Config.GambleGoldStop = 500000;

	// List of item names or classids for gambling. Check libs/NTItemAlias.dbl file for other item classids.
	Config.GambleItems.push("Amulet");
	//Config.GambleItems.push("Ring");
	//Config.GambleItems.push("Circlet");
	//Config.GambleItems.push("Coronet");
`

**Comment by aochalkov** [comment]
Bot gambles, but he didn't go for amulets if has all other materials :(

**Comment by InterestingIndeed** [comment]
So the gambling part works, but the cubing part doesn't?


Do you have this set to true? 

```
	/* Cubing config. All recipe names are available in Templates/Cubing.txt. For item names/classids check NTItemAlias.dbl
	 * The format is Config.Recipes.push([recipe_name, item_name_or_classid, etherealness]). Etherealness is optional and only applies to some recipes.
	 */
	Config.Cubing = true; // Set to true to enable cubing.

	// Ingredients for the following recipes will be auto-picked, for classids check libs/NTItemAlias.dbl

```

Additionally, this has to be uncommented as well

`Config.Recipes.push([Recipe.Caster.Amulet]); // Craft Caster Amulet`

**Comment by aochalkov** [comment]
Cubing true, amulet uncommented. Gambling true. Mats (except amulet in pick list). When bot have pamethyst, ral, jewel, he doesn't go for amulets. Or should I just wait when bot will have enough gold and go gamble?

**Comment by InterestingIndeed** [comment]
You should check which part of the script isn't working in detail. You said the gambling works and you end up with the desired item. I am unsure if that item gets "blocked" from further crafting in the first place.

Try the following: 
Give the char all the items that are needed for crafting the amulet. Make sure cube is empty. Check your pickit for amulets. The amulet that is currently on the character should not be on the pickit (to make sure pickit doesnt override crafting). Let the bot run without the gambling option, soley the crafting option should run. If that doesnt work, you know the problem lies within the crafting. If it crafting works, there might be a conflict between pickit and crafting.

**Comment by aochalkov** [comment]
Everything works. Just needed some patience =)

**Comment by danmm55** [comment]
mine isnt crafting or cubing anything except gems. everything in the code is correct. its the same as i use for all my other chars. what could be the problem? Ik its not cuz i havent waited long enough. he should be crafting...
