### ISSUE TITLE
TIME BAN | Safe ways to run 2 bots on 2 cd keysets 1 IP with about 7 min game time with one diablo installed? | failed to create game with both chars at the same time -> actually i have 2 cd key sets, i assume it didn't work to run the second char on the second key. any way to check? i manually added (typed) the second set of keys, no file being used

### ISSUE THREAD

**Issue by loldermond** [kolton/d2bot-with-kolbot#2193]
i thought i was using a different cd key on my second char y, but they got unable to host tonight both at the same time. games were about 7 mins long.

i got d2 installed ONCE and one kolbot client.

is there any foolproof way to check if they use the same cd key? like logging in with the same account or so?

i added a cd key MANUALLY (just write down the 24digit keys and applied it to the second char, no file being used. maybe that?

05:41:54 (x) Failed to create game
05:41:56 (y) Failed to create game
05:43:12 (x) Failed to create game
05:43:14 (y) Failed to create game
05:44:31 (x) Failed to create game
05:44:33 (y) Failed to create game
05:45:49 (x) Failed to create game

**Comment by Fa-b** [comment]
Are you using the same game.exe path for both bots? If so, copy paste the installation directory and use that for the second.

**Comment by loldermond** [comment]
i do. means i copy the whole diablo 2 folder with all the loose files?

ps - maybe that was not the issue. i've recently read i needed to configure 15 minutes games per bot with one ip. could that be the issue?

**Comment by Fa-b** [comment]
wherever you want it.. 7 minutes per bot should be fine I guess. For how long is it working before you have these issues? Maybe the actual game times are shorter. I was running 5 min games the other night without an issue (2 bots, same game though)

**Comment by loldermond** [comment]
about 4 hours.
if i run the same game, i could make it 5-7 mins again instead of 15. i think i'll approach that. so i need to read a lot about leecher configuration i guess. any page to refer to? thanks so far

**Comment by InterestingIndeed** [comment]
Id recommend creating a "set" of CD keys named (1) and (2) and just insert one key in each "set" (so its not a true set, but you get what I mean). Then you just give each bot one of the sets, that helps with not mixing them up.

The restriction to creating games seems be connected to the IP as well (I cant find the blizzard post for that), limited to 100games per 12 hours. To reach that, you would have to create 100 games that last shorter than 7.2minutes. Considering crashes and delays between games (presetted delay is 20seconds) 7minutes should be fine, but I would aim for a bit more (or increasing delays between games). If you run 2 bots that each create games, you will reach the point much earlier, so that might be part of your problem. 

Pros of multiple bots in one game:
- more runes
- less chicken
- chars level faster
- more space (setting up automule isnt necessary depending on your pickit)
- you can put individual tasks/pickits to seperate chars (eg make one char collect spirit packs only)

Cons:
- less items (can be fixed by having pure mf chars in the game)

Setting up leaders/leechers actually is pretty easy. I recommend putting them in the same channel and putting them on each others friendlist. Try to figure out how you get them to join the same game, then configure the runs from there on. 

Have one char do the "full" mf run (if thats what you are after) and the other guys just wait for tps to cs/throne. If you spread them out, they might get out of synch to much (one bot is still mfing and missing diablo or something), but it really depends on what you want to do.

**Comment by InterestingIndeed** [comment]
> Thanks for the details. I didn't know the exact restrictions in terms of game creation were known that well. Are those limited to game creations or does joining games count similarly?
> For MFing I'm doing as you described using BotChannel starter on the follower. Just have to make sure the follower(s) make their way to diablo and baal faster than the leader, works fine.

The restrictions are for creating games, not joins. First time I can help you out with something and not the other way round ;)
