### ISSUE TITLE
Recent string of deaths

### ISSUE THREAD

**Issue by ckelly44** [kolton/d2bot-with-kolbot#2417]
Hey guys,

I have been getting a ton of hc deaths compared to last year when I was very active - I'm talking at least a 20 to 1 increase.  I haven't changed what I've been doing. I run three windows on the same computer and same IP. But it will also happen with 2 instances, even 1. The deaths are logged correctly less than half the time, usually I just get something like this...

07:46:43 (character) Life Chicken (327/1013) to Ghoul in Catacombs Level 4. Ping: 94
07:53:18 (character) Failed to create game
07:53:40 (character) Failed to create game
07:54:03 (character) Failed to create game
07:54:26 (character) Failed to create game
07:54:49 (character) Failed to create game

I play on bnet, I have a wired connection and my chicken is 50%. I'm not unfamiliar with this application and have a fairly strong understanding of the basics. I'm wondering if this ping is too high? a lot can happen in 94ms. But that seems to be a standard ping on the servers these days. Just ran three tests on meternet and averaged 19ms, max 29ms, and jitter 3.8ms.

Any ideas?

Thanks guys.

edit: I have also used pingquit. But I'm not sure what a good setting is considering that my ping always seems to bounce over 100 which already seems horrible. I have dabbled with 300 for 3 seconds and even that triggers frequently. It tends to result in realm downs rapidly. When I don't set it at all, like in the case of using a couple of follower bots with a leader, I never seem to have any deaths, everyone quits on time. The difference is that they are in the same game, could multiple games matter?

**Comment by DarkHorseDre** [comment]
I was using
```js
Config.PingQuit = [{Ping: 1000, Duration: 2}];
```
which worked fine - better to be overly cautious than pushing up daisies.
(ping under 1000 is nothing for blizz servers, and d2 in general IMO - as I've seen longer rollbacks whilst playing and been fine if not in thick battle in hell)

also when testing ping, remember that it's ping between you and the servers, so 3rd party ping tools only tell part of the story (Blizz servers can give latency) - I used to test against europe.battle.net or whatever the name was (and there was a blizzard net test app too)

anyway, not sure why you're getting the deaths as I'm not running any bots, but protect with ping quit - duration is probably more important as the longer the delay, the more damage you will take before the client catches up, so just quit.

(FYI my chicken on hc was lower than 50% but ping quit was more sensitive (and joovs used at the right point to reduce chickens)).

also look into having followers exit (staggered) when leader does (if you havent already) as sometimes followers die without leader due to lack of bo/dps cover etc. (depends on how independent your toons are) - I often saw things unravel quickly once the leader quit/died.

**Comment by ckelly44** [comment]
I'm glad I'm not the only one with crazy lag spikes on battlenet! That makes me feel better, I thought I was losing it regularly seeing it pop over 200, 300. I will try the config you suggest, thanks. 

I had another thought, sometimes when I try to 'save and exit' the d2 window will go 'not responding', freeze up, and close a few seconds later. I'm wondering if that could be what is happening; have you ever seen anything like that? 

I looked at the chicken code and noticed it calls for the quit function, but there is also a quitgame function that kills the process entirely. That would lead to more real downs and such but I bet it would kill the connection more smoothly. Any thoughts on this?

**Comment by ckelly44** [comment]
Lost another one yesterday with new settings and without any indication at all. Not even a chicken, just checked and character was dead. I'm thinking it must be on my end.

**Comment by DarkHorseDre** [comment]
Damn - well if it didn't happen before, maybe.
you really need to watch the bot.

I saw my bot die as it tried to tp to town whilst being attacked, and it couldn't so died trying.. other time mf helper issues.. other was when leader left followers..  so watch it to see what is occurring - even if you dont see a death you'll see it come close to death

i'd also test in single player - copy your toon files to the save folder and spin it up and test

I have seem the close crash (infact it usually crashes when exiting games etc - especially if I have paused it then resumed)

>I looked at the chicken code and noticed it calls for the quit function, but there is also a quit-game function that kills the process entirely. That would lead to more real downs and such but I bet it would kill the connection more smoothly. Any thoughts on this?

damn for sure! I havent looked at the code but there is probably a good reason for quitting the game but you are right, it would contribute to realm downs, especially if more than 1 toon does it at once.

I used a staggered quit my mate gave me (now part of code) to stagger the exits but they didnt kill the window

**Comment by ckelly44** [comment]
I'm running ancient tunnels, crypt, mausoleum and Andariel. I've had deaths in all of them, but AT is rough, lots of damage very suddenly - even slight latency can royally screw you. I have seen things like the bot getting caught in some type of pather retry loop and ignoring enemies.

I'll have to test offline like you say to get some definitive answers but I bet my connection is dropping packets or something.

> I have seem the close crash (infact it usually crashes when exiting games etc - especially if I have paused it then resumed)
I didn't notice this correlation! I thought it was random and it is so annoying, because if it happens when you were near enemies it is terrifying lol.

**Comment by DarkHorseDre** [comment]
ah i see - i guess SP testing is only worth doing to check your setup and test how much chicken/pot drinking thresholds you need as a **minimum** but you still need to test on bnet for latency etc.

>I didn't notice this correlation! I thought it was random and it is so annoying, because if it happens when you were near enemies it is terrifying lol.

well lets call it an assumption on my part for now :)
Yeah nearly always get a crash at some point if I pause and resume (usually when I change things, but this is not definitive). when it does crash, the manager goes out of sync thinking game is running, then hang, then restart (with crashdelay) - happens a lot on SP IIRC - I have been doing some testing recently and will let you know.

test your ping/tracert against your bnet server - I swear there used to be a test tool I had from blizz but I cant find it now..
also add the `-sleepy` flag to the profile params if you havent already.

maybe log to file your `me.ping` every couple seconds so you build up a profile? also note it may not be net latency but other (cpu/dps etc) lag, like when there's a lot going on in-game - I'm not 100% sure but then d2 has always had issues..

**Comment by ckelly44** [comment]
So, I lost another one. And again there was no indication at all, no chicken even. Just a bunch of failed to join. I run StarTrinity continuous speed test which repeatedly pings their server ever second and will track packet loss, ping rate, and speed loss. It showed some downtime but it was running perfectly during the death window. I was running two bots, one had no issues and did not die during that same window.

I will try to track down a way to test against the bnet server itself

I wonder if you may be on to something about the hardware being an issue. I have a very powerful machine but I'm bottlenecked with an i3 8100.  But this game is ancient lol. 

This is all very frustrating because I've used this app repeatedly in the past, always hardcore, without any issue, now suddenly I get deaths every day without indication! If it matters I'm not using this repo. I'm on the blizzhackers repo, the one recommended in the readme.

**Comment by DarkHorseDre** [comment]
RIP
I'm surprised blizz are allowing ICMP to their servers - are you sure you're hitting the IP of the server that your game is on?

tbh I dont think it's a lag thing - like I said before, the bot has failed on certain circumstances causing death (unable to enter tp's etc - which is why I disabled tp to town for pots). I've seen mfhelper issues where followers get 'lost'. a bunch of reasons - what do the logs say at the time of the death?

I doubt you are hitting a ceiling - although you can test it by looking at task manager when all bots are running - cpu utilisation per process and in total will tell ya.
did you enable the `-sleepy` parameter?

is the bot the leader or the follower? which scripts are running?

re: repo - doesn't matter as much as your config and the errors/behaviour at time of death (as we seem to have ruled out latency as a cause)
any updates recently? I've seen a few but not botting so not updated..

**Comment by ckelly44** [comment]
To clarify, I am pinging the StarTrinity servers, that's how that app works, it's just a simple connectivity test. 

-sleep is enabled. Each bot runs on its own, no followers.
I'm running the following, with D2BotLead :

	Scripts.Mausoleum = true;
with crypt
	Scripts.Andariel = true;
	Scripts.AncientTunnels = true;
	Scripts.Duriel = true;
	Scripts.ChestMania = true;
lk, uk, kb

Not much has changed on that repo, nothing that would make sense for these crashes I don't think.

**Comment by ckelly44** [comment]
I found the logs you were talking about, this is interesting. It looks like the last thing it did was visit a shop and then try to get to Duriel?
[04/22/20 06:26:54] D2BS 12900: ÿc7Picked up ÿc1Greater Healing Potion ÿc0(ilvl 1) (mykolton.nip #694)
[04/22/20 06:26:54] D2BS 12900: ÿc7Picked up ÿc1Greater Healing Potion ÿc0(ilvl 1) (mykolton.nip #694)
[04/22/20 06:26:55] D2BS 12900: ÿc7Picked up ÿc3Grand Charm ÿc0(ilvl 85) (mykolton.nip #784)
[04/22/20 06:26:55] D2BS 12900: ÿc7Picked up ÿc1Super Healing Potion ÿc0(ilvl 1) (mykolton.nip #695)
[04/22/20 06:26:59] D2BS 12900: ÿc2Starting script: ÿc9Duriel
[04/22/20 06:26:59] D2BS 12900: initNPC: heal
[04/22/20 06:27:06] D2BS 12900: initNPC: identify
[04/22/20 06:27:09] D2BS 12900: move retry 1
[04/22/20 06:27:17] D2BS 12900: ÿc4MiniShopBotÿc0: Scanning 53 items.
[04/22/20 06:27:35] D2BS 12900: move retry 1
[04/22/20 06:27:39] D2BS 12900: move retry 1
[04/22/20 06:27:43] D2BS 12900: move retry 1
[04/22/20 06:27:47] D2BS 12900: move retry 1
[04/22/20 06:27:51] D2BS 12900: move retry 1
[04/22/20 06:27:55] D2BS 12900: move retry 1
[04/22/20 06:27:59] D2BS 12900: move retry 1
[04/22/20 06:28:02] D2BS 12900: Script default.dbj ended
[04/22/20 06:28:02] D2BS 12900: Script tools\toolsthread.js ended
[04/22/20 06:28:02] D2BS 12900: Script tools\townchicken.js ended
[04/22/20 06:28:05] D2BS 12900: updating runs
[04/22/20 06:28:17] D2BS 12900: Creating Game: nex2116
[04/22/20 06:28:40] D2BS 12900: Creating Game: nex2117
[04/22/20 06:29:03] D2BS 12900: Creating Game: nex2118
[04/22/20 06:29:25] D2BS 12900: Creating Game: nex2119
[04/22/20 06:29:48] D2BS 12900: Creating Game: nex2120
[04/22/20 06:30:11] D2BS 12900: Creating Game: nex2121
[04/22/20 06:30:34] D2BS 12900: Creating Game: nex2122
[04/22/20 06:30:57] D2BS 12900: Creating Game: nex2123
[04/22/20 06:31:20] D2BS 12900: Creating Game: nex2124
[04/22/20 06:31:43] D2BS 12900: Creating Game: nex2125
[04/22/20 06:32:06] D2BS 12900: Creating Game: nex2126
[04/22/20 06:32:29] D2BS 12900: Creating Game: nex2127

**Comment by DarkHorseDre** [comment]
ok cool

towncheck - yeah i disabled that as it can die if it cannot enter the portal.  same with followers and mfhelper IIRC
instead it buys pots when next in town, and enabled greater, super and joov pot collection in pickit to avoid running out

as for repo: if youre happy that nothing changed, then maybe attack config, skills, gear etc? anything that causes bot to get hurt more/do less damage/not deal with mobs/immunes effectively?  when i see l33t bots running I realise the bot is geared towards well equipped bots (whereas I, for example, love a cheap hammerdin :) )

move retry's happen a lot but if its only the 1 attempt its fine - but yeah bot will take damage whilst trying to move :(

feel free to add your own `D2Bot.printToConsole("",n);` lines to see when stuff happens - it's looking less and less likely to be latency ma dude..

**Comment by ckelly44** [comment]
Thanks for all your quick help brother. I build from the ground up with the typical cheap runewords, so yeah these guys aren't particularly strong. I'm not even at the cheap hammerdin point, I like to get the enigma first lol. 

Is it not strange, though, that it did the move retry 1 repeatedly? Like it just kept getting stuck again and again? My thought was that since it did occur on both characters maybe that helps direct us, this was on the other char less than a minute later and it ended abruptly as well. Is that weird for it to get in a move retry like that and then just stop running? Without any chicken or anything?

The other guy:
[04/22/20 06:28:21] D2BS 11880: move retry 1
[04/22/20 06:28:25] D2BS 11880: move retry 1
[04/22/20 06:28:29] D2BS 11880: move retry 1
[04/22/20 06:28:33] D2BS 11880: move retry 1
[04/22/20 06:28:37] D2BS 11880: move retry 1
[04/22/20 06:28:42] D2BS 11880: Script default.dbj ended
[04/22/20 06:28:42] D2BS 11880: Script tools\toolsthread.js ended
[04/22/20 06:28:42] D2BS 11880: Script tools\townchicken.js ended

**Comment by DarkHorseDre** [comment]
np bro.
lol yeah me too - i like to start totally from scratch and only wear what bots find..

yeah the retry issue happens a lot - there was a time maybe 1.5 years ago when it s happened too much, and some changes were made as it was due to object in town and not mobs.

do you know what is causing these?  cit is probably the same script and the same set of mobs/areas/doors causing this.. you need to see it.

tbh this is all speculation - you dont know why the bot stops running or how the bot dies - you've got to get some hard evidence.  I used to set time aside to watch the bot (or read/watch tv/speak on the phone) whilst the bot runs with sound on.
augment that with logging things (like the areaid, ping and location when "move retry 1" is triggered) and you will understand what is causing this, and do the same for other issues.
  
You can also get the bot to snap a screenshot as it chickens (Search the issues, it was couple months back IIRC)

as for chicken, there are things that can interrupt it, like the tp example I gave you.

move to sp, test, monitor and solve this! (you can copy and run one of the bots on sp simultaneously)

**Comment by ckelly44** [comment]
Okay, so without death it dropped a game suddenly with no mention of an error.

> do you know what is causing these? cit is probably the same script and the same set of mobs/areas/doors causing this.. you need to see it.

So, I took your advice and added my own logs. Sure enough I could see exactly where and when it got move retry locked. The thing is... I cross referenced the lock time and the eventual game drop, and it **DID** coincide with packet loss on my network tester. So now I'm even more lost...

> move to sp, test, monitor and solve this! (you can copy and run one of the bots on sp simultaneously)

Now that I've got mixed signals I think this is the best step. So you don't bot at all anymore?

**Comment by DarkHorseDre** [comment]
> Okay, so without death it dropped a game suddenly with no mention of an error.

what do you mean by "dropped a game"?

> So, I took your advice and added my own logs. Sure enough I could see exactly where and when it got move retry locked. The thing is... I cross referenced the lock time and the eventual game drop, and it **DID** coincide with packet loss on my network tester. So now I'm even more lost...

That's good - you're not lost; you now know that there is at least one example of latency causing the game to drop.. obviously if this occurs when mobs are attacking you could die before the game drops - has been happening to people since the beginning!
The important question is what size was the lag spike (in milliseconds) how long did it last?

> 
> Now that I've got mixed signals I think this is the best step. 

Yeah test in SP so you can tell if the issue relates to bnet exclusively or not.. it could be a combination of scripts and lag.
you can write `me.ping` and `me.area` when in game, to a log so you know where the toon is when lags and/or failed to move errors occur.  this will tell you a lot.
you can also take screenshots when you chicken (someone asked for that on here so you can search for it)

>So you don't bot at all anymore?
Nah, not for 1.5 years! No time. I will soon though, as I eventually merged my changes to the latest and made a few outstanding modifications.  I have done some SP testing recently to help a mate out, but thats it.

**Comment by ckelly44** [comment]
I mean the game just disconnected out of nowhere, not because of low life, it just crashed. No mention of issues in the log, the heartbeat and chicken script just suddenly ended. The lag spike lasted for maybe 20 seconds, but it's been happening a lot and I think sometimes the network tester i use doesn't catch it.

I've been on SP and no issues so far. I'm going to keep testing. I have a lot of fun messing with the code lol.

That's commitment, helping a friend out with this, it can be brutal sometimes. Thanks for all the help!

**Comment by DarkHorseDre** [comment]
> I mean the game just disconnected out of nowhere, not because of low life, it just crashed. No mention of issues in the log, the heartbeat and chicken script just suddenly ended. 

Unfortunately crashes can be common - you didnt have them before so may well be due to lag..

The lag spike lasted for maybe 20 seconds, but it's been happening a lot and I think sometimes the network tester i use doesn't catch it.

that's a hell of a long time.
as I posted before - you need to works out if the lag is on your/isp side or blizzards side.. 

> I've been on SP and no issues so far. I'm going to keep testing. I have a lot of fun messing with the code lol.

ha good on ya - somoene told me to do this as I was testing on hc.. it's so unecessary!

> That's commitment, helping a friend out with this, it can be brutal sometimes. Thanks for all the help!

np - I'm slowly getting back into this - just need to finish some stuff then pluck up the nerve to get my self-levellers setup and tweaked.. uff!

> edit: so after watching it today I realized that occasionally it would just stop and slowly pick through potions even if an enemy was right on top of it! And when I say slowly I mean it, like painfully. Anyways, the bot hit rejuvs at the right time and chickened in time as well. But, it clearly didn't have an interest in dodging.

you should record that to video when it happens and also check the ingame console to see what is going on (and check the ping) as that is weird!

**Comment by DarkHorseDre** [comment]
ps - please tell me youre not using wireless on your laptop/pc! 👀

**Comment by ckelly44** [comment]
Nope, I am on wire. I decided for now to play soft-core because I can't seem to figure out a fix. Hopefully I can learn something new in the meantime! I will update you if I find anything, please do the same for me!
