### ISSUE TITLE
maxquantity for items other than runes/gems/scrolls/keys

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2437]
Is it possible to define maxquantity for white items that are used for runewords?

I tried:
`[name] == flail && ([quality] == normal || [quality] == superior) && [flag] != ethereal # [sockets] == 4 # # [maxquantity] == 1 `
But it didn't work.

When i'm trying:
`[name] == flail # # [maxquantity] == 1 && ([quality] == normal || [quality] == superior) && [flag] != ethereal # [sockets] == 4`
Log writes me:
> Unknown 3rd part keyword: quality

Any help?
Thanks!

**Comment by DarkHorseDre** [comment]
`maxquantity` has to be placed after the second #.

So:
`[name] == flail && ([quality] == normal || [quality] == superior) && [flag] != ethereal # [sockets] == 4 # [maxquantity] == 1`

**Comment by ARkaine2** [comment]
Thanks for answer.
You helped me a lot.

And one little sub-question:
But what means and why has to be used double hash in strings like
`[name] == elrune # # [maxquantity] == 1`
?

**Comment by DarkHorseDre** [comment]
No problem.

I said:
> maxquantity has to be placed after the second #.

so if you are going to use it, ensure it is placed after a second #

I assume it is because the nip processor only expects to see it after the 2nd # - same as the 1st # - item descriptions are before the 1st # (name, type, quality etc) and modifiers after 1st (sockets, skills, res etc)
