### ISSUE TITLE
Sell items for gold

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2451]
Is it possible to specify bot to pick some WHITE items (like armors [with high def], wands, specters [with skills] etc) and ALWAYS to sell them?
And how to do that?

Thanks.

**Comment by inherithandle** [comment]
Yes. you need to put this statement into your .nip file:
```
[type] == armor && [class] >= exceptional && [quality] >= normal && [quality] <= rare # [defense] >= 4000
```
the conditions before `#` make your bot pick an (normal or superior or magic or rare or unique) armor which has the class exceptional or elite. the condition after `#`, [defense] >= 4000 , tells your bot to keep it or sell it. your bot always sell it to NPC, since any armor with defense 4000 doesn't exists.

**Comment by ARkaine2** [comment]
Thanks. Your answer is really helpful.
Can you please tell what stat can be used for weapons (like wands/scepters/staves)?

**Comment by inherithandle** [comment]
I think it would be:
```
([type] == staff || [type] == wand || [type] == scepter) && [quality] >= normal && [class] >= exceptional # [skillbonespear] > 4
```
as in armor case, since any staff, wand and scepter with the property 4+ Bone Spear, your bot always sell those to NPC.

**Comment by DarkHorseDre** [comment]
Guys, I have stumbled across a simpler way, whilst reading the docs - https://github.com/blizzhackers/documentation/blob/master/kolbot/MiscellaneousOptions.md/#picking-and-selling-valuable-items
