### ISSUE TITLE
How to skip townchores inbetween few scripts?

### ISSUE THREAD

**Issue by WooFelele** [kolton/d2bot-with-kolbot#2667]
I wonder if it's possible to get rid of the annoying towning while doing act 5 bosses that spawn in the same area. I would like my hammerdin to do Shenk stuff, town, kill Eyeback and then go straight for Sharptooth and Thresh Socket without making his way through town.

I've tried to modify the Sharptooth,js and ThreshSocket.js by deleting first few lines, but it ended up throwing an error with line #229 in Attack.js script.

**Comment by gtoilet** [comment]
// 	Town.doChores();

**Comment by DarkHorseDre** [comment]
each boss function/script does similar things:
goto town if not in town
town chores
wp
travel to boss
kill

so if you want to join them and avoid going to town (just travel from eyeback to sharptooth to thresh), you'd have to essentially merge the scripts.

make a copy of eyeback and add the contents of threshsocket after eyeback is killed so that it uses the commands to tele to the location of thersh, and then again for sharptooth.

**Comment by ARkaine2** [comment]
What is Town(do)Chores?

**Comment by gtoilet** [comment]
the function that controls buying scrolls/keys/repair ... etc

**Comment by WooFelele** [comment]
> each boss function/script does similar things:
> goto town if not in town
> town chores
> wp
> travel to boss
> kill
> 
> so if you want to join them and avoid going to town (just travel from eyeback to sharptooth to thresh), you'd have to essentially merge the scripts.
> 
> make a copy of eyeback and add the contents of threshsocket after eyeback is killed so that it uses the commands to tele to the location of thersh, and then again for sharptooth.

I've made something like this: https://pastebin.com/dsFz0aKv

Sadly it doesn't work properly...It kills Eyeback, moves to the Sharptooth's location (AND EVEN KILLS IT), but then this error shows up - "Error in Eyeback (attack.js #229) Attack.kill: Target not found" - and it skips the rest of the script

**Comment by DarkHorseDre** [comment]
You didn't check the code for sharptooth - it uses a different wp

**Comment by DarkHorseDre** [comment]
Oops - I don't know much about these act 5 bosses, areas and the scripts..

the original scripts take specific wp then aim for a preset unit for that area.. so its inflexible.  not only that but for some reason sharptooth isn't there when you get that error - if I go there first he is so that's what I've done.

I've also used pather.journeyTo to travel between places rather than use tp+wp.  there will be better ways of doing this but I'm outta time and this seems to work quickly - let me know if you find bugs

https://pastebin.com/sSwv9e16

Also rename the file youve made and make the function within the same name, then add a new `scripts.newname = true;` to char config - that way the original eyeback file is untouched (so you can upgrade it, revert etc in the future).

**Comment by WooFelele** [comment]
> Oops - I don't know much about these act 5 bosses, areas and the scripts..
> 
> the original scripts take specific wp then aim for a preset unit for that area.. so its inflexible. not only that but for some reason sharptooth isn't there when you get that error - if I go there first he is so that's what I've done.
> 
> I've also used pather.journeyTo to travel between places rather than use tp+wp. there will be better ways of doing this but I'm outta time and this seems to work quickly - let me know if you find bugs
> 
> https://pastebin.com/sSwv9e16
> 
> Also rename the file youve made and make the function within the same name, then add a new `scripts.newname = true;` to char config - that way the original eyeback file is untouched (so you can upgrade it, revert etc in the future).

Your file seems to work perfectly, just like I imagined it to be, so far no bugs found. Thank you very much for the help especially if you're short on time : )

**Comment by DarkHorseDre** [comment]
No worries man - my main concern is whether the bot is moving between bosses in an efficient route - its moves too quickly for me to tell and I dont know my way around most parts of act 5!

but glad it works
