### ISSUE TITLE
Merc don't use healing potions but player does.

### ISSUE THREAD

**Issue by bagana100** [kolton/d2bot-with-kolbot#2826]
Greetings community.
About potion settings , we just have to key in percenties that we want to use.
But how come that it works to me and not to my merc?

**Comment by DarkHorseDre** [comment]
.. what have you set the merc potion setting to?

**Comment by bagana100** [comment]
I had set it to 95% for healing potion and 50% for rj. 

// Potion settings
Config.UseHP = 90; // Drink a healing potion if life is under designated percent.
Config.UseRejuvHP = 25; // Drink a rejuvenation potion if life is under designated percent.
Config.UseMP = 75; // Drink a mana potion if mana is under designated percent.
Config.UseRejuvMP = 10; // Drink a rejuvenation potion if mana is under designated percent.
Config.UseMercHP = 95; // Give a healing potion to your merc if his/her life is under designated percent.
Config.UseMercRejuv = 50; // Give a rejuvenation potion to your merc if his/her life is under designated percent.

**Comment by DarkHorseDre** [comment]
ok, that looks fine

please paste your config to pastebin.com or similar site and paste the generated link to it here

**Comment by bagana100** [comment]
https://pastebin.com/BaU8YiML

Thx for checking!! And it's my first time to use pastebin.com , let me know if I made it wrong.

**Comment by DarkHorseDre** [comment]
no that was perfect - you even added javascript highligting which really helps :)

The problem is you have not set this to true:
`Config.UseMerc = false; // Use merc. This is ignored and always false in d2classic.`

You probably had the merc from before and it will not be cancelled, but if it died it would not be rehired because of this setting. the bot is not watching the merc and therefore isnt using potions

Also consider mercwatch setting.

I would **Strongly** suggest you/everyone reads EVERY line of the config as there are useful settings in there that answer most questions.

**Comment by bagana100** [comment]
Thx again , because my mother language is not English so it's a little bit hard for me to check everyline correctly. So lucky for me to find this site , it takes time but worth :)

**Comment by DarkHorseDre** [comment]
yeah thats ok - paste the comments/whole config into google translate :) 

good luck
