### ISSUE TITLE
Trav leecher doesnt return to town

### ISSUE THREAD

**Issue by boddhisatra** [kolton/d2bot-with-kolbot#287]
After the leader kills trav, the leecher sits by the back portal spot, but doesnt return to town or end script. Any fixes?

**Comment by StoneOfJordan** [comment]
What's the leader script? I'll update it when I have some time.

**Comment by boddhisatra** [comment]
The leader works fine, but its the leecher that just idles after the trav kill.

Leader is pushing these lines:
Scripts.Travincal = true;					l
		Config.Travincal.PortalLeech = true; // Set to true to open a portal for leechers.

Leecher uses:
Scripts.TravincalLeech = true; // Enters portal at back of Travincal.
		Config.TravincalLeech.Helper = false; // If set to true the character will teleport to the stairs and help attack.

**Comment by StoneOfJordan** [comment]
Alright.

[Travincal.js](https://gist.github.com/StoneOfJordan/8293c5ffe7a99093c435901418443e1f)
[TravincalLeech.js](https://gist.github.com/StoneOfJordan/3e7b9be148b300ddf35428bb20f59757)

TravincalLeech:
- Replaced a loop that caused the mentioned issue.
- Added leave message via receiveCopyData that ends the area 83 loop.

Travincal.js:
- Added sendCopyData leave message.

Uhm, this will only really help you if you have one setup/game that runs those scripts, since the leave message that I added will be sent to all running clients, (which may  also run that script in a different game).
Let me know if you want a version that doesn't care about that, would require more edits though.

**Comment by boddhisatra** [comment]
Hi SOJ, thanks for coming up with those edits so quickly. It works perfectly now! Now after the trav council kill, the leecher will move onto the next script. 

As you noted, this fix only works if the party is running on the same manager. When they are on separate managers, like with a VM/VPN setup and two separate managers, the trav leecher will just linger at the back portal spot until the game is over, like the default version. 

While it would be helpful to have to trav leech working properly when on separate managers, it's not a big deal or priority issue anymore. I could see this being a useful function for people trying to level  bumpers.

**Comment by StoneOfJordan** [comment]
I was talking about sending the leave messasge only to specified profiles (instead of all running profiles) on one machine. "Cross machine communication" would be a different cup of tea.

**Comment by XoniBlue** [comment]
this issue is still happening and i cant access the edits that have been made, any ideas?
