### ISSUE TITLE
Stagger time between games for multiple leads

### ISSUE THREAD

**Issue by Hopes92** [kolton/d2bot-with-kolbot#294]
Hello,

I wondered if it would be a nice addition to have a variable set time between making games when running more than 1 leader (or solo chars).
This feature was added to etal after blizzards "server down" policy changed from games / cd key to games / ip.
It is claimed, that it helps to prevent "server down" issues by making sure that there are at least 2 minutes between the creation of a new game.
A workaround would obviously be to just have the mingametime exceed the the time the run takes and then time it for running more than 1 lead, but that would make it impossible to have random gametimes which I believe is necessary as well in order to avoid issues.

I sadly lack the skills to do that on my own, but if someone whos capable adding that deems it a good idea, Id be glad to see it added !
(Ive been happy enough to do simple modifications to existing scripts and have them work the way I want them to. In this case however I cant find what I need in the existing entry scripts to achieve that goal).

Link to etal forum post:
https://www.projectetal.com/forums/threads/scripting-delays-in-the-create-game-entries-need-testers.34189/

Thanks in advance!

**Comment by StoneOfJordan** [comment]
rand(x, y); will do more for you than that system. =)

**Comment by Hopes92** [comment]
Thanks for the fast answer.
Thats one of the commands I was using over and over again in almost all scripts for multiple purposes after I first came across it here.
https://github.com/kolton/d2bot-with-kolbot/pull/224/files
I tried to use the stuff there to keep silent leech with teleport chars opening portal and having non teleport chars join in for the bosses basically like the MFHelper script, but without chat !
The one thing I never understood however, was how the heck that "case 6969" is working (as to why it is 6969 and how can I use something similar to basically add in a "safe check" for other scripts). 
That left me with a non "safe check" method where the chars just idle and take the first tp opened to the area which works perfectly fine as well :) 
- Nihlathak seems to spawn at random coordinates though which makes that a little more difficult it seems ~~

But back to rand(x, y) command.
Using it on "CreateGameDelay" was kinda obvious, but do you refer to using it for "MinGameTime" as well ? ~~
That would make something like
MinGameTime : rand( 520, 700), // think that 3 minutes is enough for 2 leads or rather go for a large random time of "CreateGameDelay" to something like 3 minutes ?

**Comment by StoneOfJordan** [comment]
1)
Take a look at the sendCopyData function that D2BS provides: http://docs.d2bs.org/group__globalFunctions.html#gad4e03d1abafaa3beab0e1cbb90ca8e37
```int sendCopyData ( String windowClassName, String windowName, int32_t nModeId, String data )```

6969 is just a random number picked for the mode. It has no meaning beyond that. You'll send the nModeId integer and data string to the specified window. The setup that you're talking about handles that message by checking which nModeId was received since the message wasn't important in that case. The switch is also redundant because of that.

Here's an example of how you could use send/receiveCopyData:
```	var inputMode = 1337, // some number of your choice
		inputMsg = "hej"; // some message
		
	sendCopyData(null, profileName, inputMode, inputMsg);
	
	addEventListener('copydata', // for recipient
		function receiveCopyData(mode, msg) {
			if (mode === inputMode && msg === inputMsg) { // check input data (msg) & mode
				doSomething();
			}
		} 
	);```

2)
You can get Nihlathak's coordinates using the getPresetUnit function, Nihlthak's id is 462 I believe.
```Pather.moveToPreset(me.area, 2, 462, 0, 0, false, true);``` this Pather function will also do the job if you're in Nihlathak's area. 

3)
Pather.js is the right place to look for. Just add a print function to whatever function you'd like to look at.

4)
The current core in this repository runs on 1.14d, no version hack required.

**Comment by StoneOfJordan** [comment]
1)
Take a look at the sendCopyData function that D2BS provides: http://docs.d2bs.org/group__globalFunctions.html#gad4e03d1abafaa3beab0e1cbb90ca8e37
```int sendCopyData ( String windowClassName, String windowName, int32_t nModeId, String data )```

6969 is just a random number picked for the mode. It has no meaning beyond that. You'll send the nModeId integer and data string to the specified window. The setup that you're talking about handles that message by checking which nModeId was received since the message wasn't important in that case. The switch is also redundant because of that.

Here's an example of how you could use send/receiveCopyData:
```
	var inputMode = 1337, // some number of your choice
		inputMsg = "hej"; // some message
		
	sendCopyData(null, profileName, inputMode, inputMsg);
	
	addEventListener('copydata', // for recipient
		function receiveCopyData(mode, msg) {
			if (mode === inputMode && msg === inputMsg) { // check input data (msg) & mode
				doSomething();
			}
		} 
	);
```

2)
You can get Nihlathak's coordinates using the getPresetUnit function, Nihlthak's id is 462 I believe.
```Pather.moveToPreset(me.area, 2, 462, 0, 0, false, true);``` this Pather function will also do the job if you're in Nihlathak's area. 

3)
Pather.js is the right place to look for. Just add a print function to whatever function you'd like to look at.

4)
The current core in this repository runs on 1.14d, no version hack required.

**Comment by Hopes92** [comment]
Awesome!
Big thanks again.

1)

Ill definately be playing around with that :)

2)

Pather.moveToPreset(me.area, 2, 462, 0, 0, false, true);
I havent found moveToPreset or Pather in that list of functions. Unclear to me after the first look at it is: 
me.area -> okay
2 -> meaning ? 
462 -> nihlathak okay
0, 0, -> always 0 as decribed in Preset functions ?
false -> refering to ?
true -> refering to ?

3)

yeah prolly doing some testruns till I find a sweet spot for me! - can force a new ip from provider via a very old router with a software coded mac address in case of s/d <3

4)

gonna work my file through the lines till I find what im looking for!

5)

thinking about using a clean install then, but prolly gonna delete blizzarderror and systemsurvey just because ^^



Sadly I wont be at home at all tomorrow, but Ill take my time with the info on friday / saturday!

**Comment by StoneOfJordan** [comment]
It's not a core function, you'll find it in the kolton lib.

```	/*
		Pather.moveToPreset(area, unitType, unitId, offX, offY, clearPath, pop);
		area - area of the preset unit
		unitType - type of the preset unit
		unitId - preset unit id
		offX - offset from unit's x coord
		offY - offset from unit's x coord
		clearPath - kill monsters while moving
		pop - remove last node
	*/
```

**Comment by Hopes92** [comment]
Just took a look after coming home.
I feel kinda stupid now... its indeed explained from line 121 to 126 in pather.js ~~
I guess the "pather" in front shouldve given me already the answer as to where to search, but Ive learned again :)

Thanks, Ill try play with it tomorrow!

**Comment by Hopes92** [comment]
For Nihlathaks coordinates I am a little confused...
Thats the function that the standard Nihlathak script uses
`Pather.moveToPreset(me.area, 2, 462, 0, 0, false, true);`
but putting a 
`Pather.makePortal();`
in the next line opens a portal at a rather big distance from nihlathak which makes this impossible for walking chars.

Strange to my mind, as the offset for x and y should be 0 and thus the tp should be opened almost on top of him!

**Comment by D2Patch09** [comment]
Hopes if you can, I'm needing help with the sendcopydata function to replace chat commands.
