### ISSUE TITLE
Does anyonw know how to stop bots from picking up items to sell for gold? for sum reason their programmed to drop gold on teh ground

### ISSUE THREAD

**Issue by danmm55** [kolton/d2bot-with-kolbot#3116]
can anyone explain how to stop bots from wasting most of their time dropping gold on the ground for no reason? ive seen a couple posts about this but nobody seems to have any idea how to make them not pick up items for gold. for sum reason they are programmed to sell items for gold non stop. my bot literally picks up every items that drops and wants to sell it even tho nobody needs gold especially when your already maxed... please just tell us how to fix it. i already tried pasting config low gold in my chars config. that doesnt work.

**Comment by danmm55** [comment]
Ive been trying to get my bots to not pick up gold for months. can somebody please just tell me how to do it. I read other posts about this and nobody that knows how will reply. its only a bunch of other ppl that dont know as well that will respond, its really getting irritating. I could explain it easily in one sentence if i knew how

**Comment by DarkHorseDre** [comment]
Your title is too long and is confusing as you conflate 4 different things and duplicate 1:
1: bot dropping gold 
2: picking up items for gold
3: selling items that it has picked
4: config lowgold in config
5: get bot to not pickup gold

You need to understand the game, the bot and be clear in what you are asking.
I have seen your posts to 2 year old closed posts - that's never a good idea btw.  neither is being rude to people when you're confusing your issues with theirs.

You have misunderstood the issues being reported and expected it to work for you.

I think no3 is likely to be your complaint.

Let me start by answering 1-5 above. if you need more info, search the threads using the right info.  I won't respond a second time.

1. The **BOT** only drops gold when you're running scripts that need to drop gold for other players (Gambling etc). 
The **GAME** drops gold if the character capacity is maxed and new gold is gained and this cannot be changed ofc.

2. This happens if config lowgold is set or if it is not then IIRC a default limit is met. **to be clear** config lowgold collects crap items to sell if your gold is below the set threshold (the threads you miss-commented on explain how this works) - this is not your issue, obviously.

3. selling items it has picked that do not match the pickit is **default behaviour**.  The idea is that the items are sold to clear the stash as the bot does town chores when the bot is at the shop anyway.  if this somehow offends you, either gamble your gold before it gets maxed, or drop the items.  ID'ing at cain or using fieldid should drop by default, so I don't know what the issue is?

If those 2 things somehow do not work for you, then the threads you read show how to change the code to sell/drop items. You can also adapt this guide to have the items dropped: https://github.com/blizzhackers/documentation/blob/master/kolbot/MiscellaneousOptions.md/#use-Cain-and-sell-items

4. Config lowgold only gets triggered if your gold goes beneath the threshold as you would have read, but you say your gold is maxed and the GAME drops any new gold from sales as you say, so this is irrelevant to your issue - if you understood the threads you would not have set this at all.

5. if you do not have gold in your pickit, it wont pick gold.  if you think you removed all gold entries from all loaded pickits and reloaded the bot and it still picks, you've done something wrong.  Change whatever you customisations you made or download the files again.

**Comment by danmm55** [comment]
I was being ssarcastic. The bots are programmed to keep selling items that are junk even once they have max gold. hence they are programmed to drop gold on the ground for no reason.. many other ppl have also had this problem. I couldnt find any answers. eventually i stumbled upon this thing called field ID. Its makes the repeated picking up of items a non issue. for some reason that is a generic setting on the program. Ive seen bots that go to town to id stuff and it takes them 20 mins to doa  cbaal run. thats what was happening and i didnt understand why they would be programmed to do that. still doesnt make much sense. If i was a programmer id make them not pick up junk to sell when they have max gold or a max stash. that would be vastly superior. Its still stupid that they waste time to pick up the stuff and id it.

**Comment by danmm55** [comment]
So yeah if you have a program change the settings to field id otherwise they go to town every few seconds and its ridiculously stupid.
