### ISSUE TITLE
Connection Interupted

### ISSUE THREAD

**Issue by iamenvision** [kolton/d2bot-with-kolbot#325]
So here's what I did to install it;

- Got installer from torrent.
- Updated to 1.14d
- Configured bot settings.
- Bot logs in, joins game. Connection interupted when taking the waypoint. Sometimes before, sometimes after.

What am I doing wrong?

**Comment by jmkim2ea** [comment]
Yes, it is normal..because Bizzard "did" new batch that interrupt everywhere. I can't do anything with kolbot now.

**Comment by iamenvision** [comment]
So what do all those botter use now?

**Comment by kamikazzi1** [comment]
Are you running the latest version of Kolbot?

**Comment by jmkim2ea** [comment]
Yes, I am running the latest kolbot with autosmurf.js file. 
Actually Autosmurf is now blocked with interrupted black screen.
And Dia + Baal Run with Kolbot file, it is work  with many black screen.
So I suggest you that wait until next Ladder (12-12-2017) and wait Kolbot Update.

**Comment by iamenvision** [comment]
I've tried the following;
- Installations using a non-web download from blizzard.
- 1.13d installation, with 1.13d or 1.14d setting to connect.
- 1.14d installation, with 1.13d or 1.14d setting to connect.
- With version hack, game.exe loads, but never shows or seems to do anything.
- Without version hack, game loads, logs in, creates game, goes to wp, starts to run to do whatever is first to do in config, comes back to wp and C/I.

**Comment by hehewhatitdo** [comment]
How long have you been having this issue? How long had you been botting prior to this issue?

I haven't botted since the recent banwave, but I would get connection interrupted when the bot would try to use a waypoint that I didn't have. For example, if the bot was set to do Duriel and if the character didn't have the Canyon waypoint, it would get connection interrupted.

Do you have the necessary waypoints? Or is this happening regardless?

**Comment by iamenvision** [comment]
I just started back after nearly 2 years of inactivity. It crashes regardless of if I have WP or not. I tried Andy (have it) and C/I.

It's really weird because it logs in, select char, makes game, takes WP, starts running in the direction to do the quest (About 5 yards), then walks back to WP and C/I.

**Comment by hehewhatitdo** [comment]
What class are you using?

**Comment by jmkim2ea** [comment]
<This is the latest Kolbot + Autosmurf.js with Bizzard new patch>
====================================
There are connection interrupted point and must have to use manually with using Autosmurf.js 
1. Act1, After Kill Andariel, tall to  Warriv and go to Act 2 (by hand)
2. Act2, After Kill Duriel, tall to Jerhyn + Meshif and go to Act 3 (by hand)
3. At the Kurast Docks(Act 3) you have Connection Interrupted because Bird Quest.(I Fixed Autosmurf.js file by myself and It is OK)
4. Act3, After kill the High Council, Sorc go to next waypoint but others have Connection interrupted.
 That's Ok, because next game is OK. 
5. Act4 is Ok 
6. Act5,  At the Anya quest, After get the anya potion, bot just stop. So manually give potion to Anya.
7. Act 5, at the Rite of Passage, after kill the Ancient, Sorc go to next waypoint but others have Connection interrupted. But next game is Ok go to Baal.
=================================================
There are all errors.

**Comment by iamenvision** [comment]
I've tried with Assassin and Paladin so far. Same results.

**Comment by StoneOfJordan** [comment]
It doesn't matter which character you're using. Which ingame script are you using (eg. Baal.js) and what exactly is it doing before the c/i occurs?

**Comment by jmkim2ea** [comment]
Jordan is right. no matter which character. 
Just use Baal.js or Diablo.js is ok. That means Dia_Baal Run is Ok. 
But when bots are playing game , many bans are occur frequently. So I just power off kolbot. :-(
Also use D2NT seems ok. but I am not sure.

**Comment by boddhisatra** [comment]
@jmkim2ea Its getting connection interrupted at the NPC interactions, because its sending packets that have been patched. I've fixed a large amount of them, by substituting code from the Rusher/Rushee scripts. However, I got banned before completely fixing it. You can try this version: https://pastebin.com/iMfwa4SL

**Comment by jmkim2ea** [comment]
@boddhisatra Thanks..I do try the AutoSmurf.js file but [https://github.com/JeanMax/AutoSmurf](url) 
this is the same thing I guess...If the two files are same. We have no hope. :-(

**Comment by Zephxroth** [comment]
Having the exact same issue i get C/I before trying to take WP. It wont run any scripts.

**Comment by boddhisatra** [comment]
WARNING to everyone that Autosmurf is not safe to use at the moment. The bot is detectable due to sending of bad packets, and you will get insta-banned. A friend just informed me earlier tonight.
