### ISSUE TITLE
Follow

### ISSUE THREAD

**Issue by Yrcraw** [kolton/d2bot-with-kolbot#358]
Is there any way to put a follow in silent mode? So that it interacts via console or something and not via in game commands?

**Comment by WiZzMaN47** [comment]
Well u could make it whisper another char but then the other char will need
to be able to respond and receive commands with whispers and even an
allowed list of people thar can give commands directly or thru proxy

On Mar 14, 2018 7:21 PM, "Yrcraw" <notifications@github.com> wrote:

Is there any way to put a follow in silent mode? So that it interacts via
console or something and not via in game commands?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kolton/d2bot-with-kolbot/issues/358>, or mute the thread

**Comment by RogersRo** [comment]
Yes, you can use the sendcopydata functions. The same way the automule communicates with other profiles.
