### ISSUE TITLE
Wind druid too near at his target monster

### ISSUE THREAD

**Issue by sineverba** [kolton/d2bot-with-kolbot#624]
Hi to all,
all works as a charm, but, I did notice that my windy druid (tornado skill) every time is too, really too near to his target.

Infector can be sometime an issue, also some other mobs. Same for Diablo and his fire ray.

I did check the specific file druid.js but I cannot find nothing for add a safe distance (only some relative to position target).

Is there a possibility to add more distance between druid and target?

Same I would say about hammerdin. It wants walk (no enigma atm) between last pack with Infector... Too brave for me :) With hdin there is a soso light that can clean in some second, no need for suicide hammerdin :)

Thank you very much

**Comment by justinpees** [comment]
is this a problem bcuz ur druid keeps dying? the reason why it is set so close is so that the nados hit 100% of the time. nados dont use Attack Rating so its really just a positioning technique. increase your block or do something else with your charcter instead of trying to alter this in the scripts because youll run into many different problems if you change that distance im sure.
