### ISSUE TITLE
Multiple .nip files

### ISSUE THREAD

**Issue by Dratos1** [kolton/d2bot-with-kolbot#807]
So I've got it running and it's working great! Since the ladder restarted, I think the default "classic.nip" won't pick up things like low shakos, vipermagi, etc, so I found a "starter.nip". 

My question is, will the two files contradict one another? If one of my file's says "sell" and the other say's "keep", will the "sell" nip superimpose itself on the "keep""? Should i remove the classic one out of the folder completely?

Sorry for any confusion!

**Comment by 5noop** [comment]
classic.nip won't pick up shakos because it's supposed to be used in classic aka no expansion

But yes you can use multiple pickit files, it's designed that way.

**Comment by jaenster** [comment]
Pickit only describes what to keep, not what to sell. It is an list of inclusion, not exclusion. If either line  matches on the given item, it keeps it. All lines are run on the specified item, if one of them matches the item, it keeps it (with some exceptions for auto equipment).

To give an example:

If you have a few pickitlines, like for example a shako, a griffon and a totally different item like a mara and the bot runs these lines on a shako it doesn't match either for a griffon or a mara, but since one of the lines matches (the one of the shako), it keeps the item.

**Comment by DarkHorseDre** [comment]
in addition to the info posted above, you need to think about what you want to keep.  quickest thing to do is search this site or google a good expansion pickit, and check the attributes as many will only pick perfect stat items (whereas I think a random shako is gg at start of season, and worry about higher def later on)

you can have more than one nip specified in config - good for having one for pots and gems and stuff, one for other items which you will update separately over time.  some people have whites, magic, uniques etc in separate, and some have season start, mid and perfect pickits :)

**Comment by Subsevendgrz** [comment]
could you post the starter.nip you found?
