### ISSUE TITLE
How can leecher open cows

### ISSUE THREAD

**Issue by Kantonov** [kolton/d2bot-with-kolbot#816]
A huge thanks to whoever tells me how to open cows with a leecher. Leader killed cow king.

**Comment by DarkHorseDre** [comment]
Hmm.. I had this thought at the end of last ladder when my leader killed king (n00b).

Looking at the `cows.js` it does everything with going to trist etc then it executes the cow level clear in one line
` this.openPortal(leg, tome);
    Pather.usePortal(39);
    Precast.doPrecast(false);
    this.clearCowLevel();`

so I would copy the cows.js to a new file (e.g. followercows.js), modify to remove the useportal, precast and clearlevel (leaving just 1 command: `this.openPortal(leg, tome)`), then add the line in follower toon config (`Scripts.followercows`), have it execute it and it should just do all the work and then quit, moving onto the mfhelper/whichever script you are using for it to leech.

The leader will need a modified script to just use the portal to cow level instead of all the other work
(`Pather.usePortal(39);`)

Timing will be important as if the leader tries to use portal before follower has completed its tasks (couple minutes with tele?) then it will fail.  the proper way to do it would have them interact, but thats beyond me, so the above is a theoretical dirty way to do it :)
ultimately, if the follower gets leg, tome and opens portal at the start of runs (couple mins) it will just miss the first couple mins of run and leader should be doing something else (unless it is only doing cows each run?) and they will both link up anyway.

LMK!

**Comment by 5noop** [comment]
You should be able to loop on the portal until you can enter it, something like that:
```
while (!Pather.usePortal(39)) {
	delay(1000);
}
```

Or maybe a better way to do it would be to loop `Pather.getPortal(39)` and once you get it you can enter.

**Comment by gtoilet** [comment]
this would be something ez to put into the follower

only thing would be is if you want it to go get the leg from trist its self or if you would drop it in town

**Comment by DarkHorseDre** [comment]
@gtoilet - he asked for info on how to do this!

**Comment by Kosoleld** [comment]
To first check if there is a portal near stash and use that instead of going to get a leg I wrote this, feel free to use it.

Paste this over the same code at the end of <Cows.js> starting with the first 2 lines

	Town.goToTown(1);
	Town.doChores();
	if (Town.move("stash")) {
	}
	
	if (Pather.usePortal(39) == false){
		leg = this.getLeg();
		tome = this.getTome();
		this.openPortal(leg, tome);
		Pather.usePortal(39);
	}
	Precast.doPrecast(false);
	this.clearCowLevel();

	return true;
}

**Comment by Kantonov** [comment]
Ok I did it, here is step by step for any one. Huge thanks to @DarkHorseDre 
1. Copy Cows.js **twice** - don't edit Cows.js - you can use it the normal way.
Rename them as follows: CowsGetter.js and CowsLead.js
2. Edit CowsGetter.js: <br />
`Edit the ~7th line from`<br />
`function Cows() {` <-- to --> `function CowsGetter() {` <br />
Put '//' in front of those bottom lines, like that: <br />
`//Pather.usePortal(39);`<br />
`//Precast.doPrecast(false);`<br />
`//this.clearCowLevel();`<br />
3. Edit CowsLead.js: <br />
Edit the ~7th line from<br />
`function Cows() {` <-- to --> `function CowsLead() {` <br />
Put '//' in front of line 200, like that: <br />
`//throw new Error("Already killed the Cow King.");`<br />
Copy and paste at the end, from line 222, should look like this:
`Town.goToTown(1);`
`Town.doChores();`
`Town.move("stash");`
`var maxSecondsWaitForLeg = 60;`
`    while (!Pather.getPortal(39)) {`
`		if(maxSecondsWaitForLeg == 0)`
`		{`
`			break;`
`		}`
`		delay(1000);`
`		maxSecondsWaitForLeg -= 1;`
`	}`
`	Pather.usePortal(39);`
`	Precast.doPrecast(false);`
`	this.clearCowLevel();`
`	return true;`
`}`<br />

4. In the config for the char that can open cows add Scripts.CowsGetter = true;<br />
5. Respectively in the char config that is going to Do the cows add Scripts.CowsLead = true;<br />
6. Do mind that Scripts are executed one by one, from up to down - I recommend putting CowsGetter and CowsLead script settings at the top of the char config, below battle orders.
<br />
**Notes:**<br />
Edit var maxSecondsWaitForLeg = 60; to whatever number of seconds you want the cow killer to wait for portal.
<br />
There is of course a better way to do this, by adding config to cows and inside spreading the logic instead of two files but anyhow, thats working.

**Comment by DarkHorseDre** [comment]
Good work bro - add your parameters to control settings (like seconds to wait etc) via config.js and char config as and when you can, to tweak & improve it. 

dont forget what @5noop said - loop/while on getportal and only use it (useportal) when its available, within the delay period.

**Comment by skyriest** [comment]
This was an amazing start.  I ended up adding 3 new scripts.  1 for making cows. 1 for killing cows but not the king, and 1 for killing the cows and the king.  Since I run hardcore on USWest with 6 chars, this has to be absolutely perfect or.... ya know...  I made my barb open the portal at the start of the game while my sorc leader runs andy, my 1st pali runs meph, my 2nd pali runs all keys, and my druid and zon wait in chaos.  After Chaos and Baal, I make my barb stand in town for 1500 seconds mingametime and only leave when my sorc leader quits.  This was extremely fun to recode/resequence and I'm very thankful for you Kantonov. Kosoleld, and DarkHorseDre

First, I added this code to each of my character profiles:

	//Cows
	Scripts.CowsMaker = false;
	Scripts.CowsKiller = false;
	Scripts.CowsKillKing = false;

Then, I was able to comment out the king identifier and badrooms in the cow code to kill the king.  Here's what that looks like, replacing the first 24 lines of code: 

/**
*	@filename	CowsKillKing.js
*	@author		kolton / mod by skyie
*	@desc		clear the Moo Moo Farm and kill the Cow King
*/

function CowsKillKing() {
	this.buildCowRooms = function () {
		var i, j, room, // kingPreset, badRooms, badRooms2,
			finalRooms = [],
			indexes = [];

//		kingPreset = getPresetUnit(me.area, 1, 773);
//		badRooms = getRoom(kingPreset.roomx * 5 + kingPreset.x, kingPreset.roomy * 5 + kingPreset.y).getNearby();
//
//		for (i = 0; i < badRooms.length; i += 1) {
//			badRooms2 = badRooms[i].getNearby();
//
//			for (j = 0; j < badRooms2.length; j += 1) {
//				if (indexes.indexOf(badRooms2[j].x + "" + badRooms2[j].y) === -1) {
//					indexes.push(badRooms2[j].x + "" + badRooms2[j].y);
//				}
//			}
//		}

		room = getRoom();




That's all it took to get this fixed. Yay!

**Comment by theBGuy** [comment]
@skyriest You could also just use blizzhackers/kolbot and I added a config option awhile back to handle this.

**Comment by skyriest** [comment]
> 

Hey theBGuy,
Thanks for letting me know. I had a lot of fun learning to modify code. Maybe it was all for nothing. 

I’ll go look for the latest info at the link you provided. Perhaps I’m using an extremely old version. Thanks again!

**Comment by theBGuy** [comment]
It's never for nothing if you learned something and enjoyed doing it. I just thought I'd let you know that it exists already.

https://github.com/blizzhackers/kolbot
