### ISSUE TITLE
"Waiting in line"...

### ISSUE THREAD

**Issue by Rocksix** [kolton/d2bot-with-kolbot#826]
Currently running two bots from the same computer with run times greater than 5 min (~12 games per hour per bot). I always get the same 10k waiting in line que around the same time at night. Is the 20 games/hour IP bound? Was wondering if I should increase run times to 7-8 minutes per bot, or if there was something in the code I was missing.

**Comment by imbalanced** [comment]
Your current run times seem too short. You may want to increase it to 8~10 minutes.

**Comment by DarkHorseDre** [comment]
I read they are IP bound.  I increased my game time to avoid the issue.

**Comment by Rocksix** [comment]
Gotcha, thanks guys. Closing this now.

**Comment by DarkHorseDre** [comment]
I know this is closed but adding as this issue is occurring more. looking at Blizz guidance: https://eu.battle.net/forums/en/bnet/topic/10100940135

.. crashes will add to disconnect (and other) counts and we are all (?) seeing more crashes.  

linking to other posts to aid grouping: https://github.com/kolton/d2bot-with-kolbot/issues/530
