### ISSUE TITLE
Config.QuitList, How to add delay, to quit few seconds after name on the list quits?

### ISSUE THREAD

**Issue by shiny001** [kolton/d2bot-with-kolbot#835]
Is it possible to add delay in Config file, so my character will have time to inspect final boss drops? As of right now, it seems like my character leaves without checking for drops.

Thank you

**Comment by imbalanced** [comment]
You have to open tools/toolsthread.js and find the following code which is near the bottom.
```js
if (quitFlag && canQuit) {
	print("ÿc8Run duration ÿc2" + ((getTickCount() - me.gamestarttime) / 1000));

	if (Config.LogExperience) {
		Experience.log();
	}

	this.checkPing(false); // In case of quitlist triggering first
	this.exit();

	break;
}
```

So before it calls this.exit() you can add add any actions that you want such as Pickit.pickItems(); for picking up items etc. or add delays. But long delay is probably not recommended because your character may be left vulnerable.

**Comment by 5noop** [comment]
Your character does not need "a delay" to inspect the drop, the function pickItems from Pickit.js does its job as it will pick every item it is supposed to pick before returning. And your character won't leave before the last function has returned.

So the only thing you need to be sure is how the last running script ends: if it ends with a Pickit.pickItems() then you are fine, otherwise you should add it.

Now if you want to be convinced you can indeed add a `delay(3000);` in the end of the script, but it's just for you to be able to visually check the remaining loot, the bot will not do anything during this time.

**Comment by shiny001** [comment]
Thank you so much guys!
@imbalanced that is exactly what i was looking for, you rock

**Comment by tylerqr** [comment]
Very helpful thread guys, thank you. I can confirm that adding a delay before this.exit() is called the bot will wait for a time before exiting the game. 

My question: 

Is there a way to get multiple followers/leechers to have different exit delay times? I'm using the JoinDelay config in D2BotChannel.dbj to spread out when my game of 6 runners all join the game, spread out over 60 seconds. But I can't figure out how to not have all 6 exit the game all at the same time. Trying to avoid RD's and "In line to create game" by doing this and increasing game length, among other tweaks. 

Thanks in advance!

**Comment by shieldarc** [comment]
Adding what? I don't see a solution here. I'm having the same damn issue and nothing seems to be working. Why make the config.quitlist be able to set a time if it doesn't even work? Fix your program!
