### ISSUE TITLE
Pause problem

### ISSUE THREAD

**Issue by tuito1** [kolton/d2bot-with-kolbot#878]
No pause key on my laptop keyboard

is there a way to change it?

**Comment by justinpees** [comment]
if youre on windows, open up the on screen keyboard and you can use the pause there like i have to do. You running windows on your mac? :P

**Comment by tuito1** [comment]
> if youre on windows, open up the on screen keyboard and you can use the pause there like i have to do. You running windows on your mac? :P

thanks for answering, Im running on windows right now so I'll try that (how do I turn that function on?)

anyway's I'd like to change the key binding since It's easier to me to pause the game

**Comment by justinpees** [comment]
start menu/all programs/accessories/ ease of use/onscreenkeyboard

**Comment by justinpees** [comment]
and make sure that the diablo window is active when you click on "pause". so in other words make sure the keyboard doesnt overlap d2 window for easier use

**Comment by tuito1** [comment]
> start menu/all programs/accessories/ ease of use/onscreenkeyboard

Thank you, It worked perfectly! :)

**Comment by justinpees** [comment]
if you have more questions for me, feel free to meet me in game :) lmk game/realm/ladder or non :)

**Comment by mppperez** [comment]
Just for everyone who don't like to use the onscreen keyboard solution since it is unhandy: just change the appropriate key codes in the code itself is easy. You can view the key codes e.g. here ```https://www.cambiaresearch.com/articles/15/javascript-char-codes-key-codes```

- in ToolsThread.js line 352. Change from
```
	// Event functions
	this.keyEvent = function (key) {
		switch (key) {
		case 19: // Pause/Break key
			this.togglePause();

			break;
```
to any else key from keycode list. E.g. 18 is ALT:
```
	// Event functions
	this.keyEvent = function (key) {
		switch (key) {
		case 114: // Pause/Break key was 19 but notebook don't have... use F3 (114) instead
			this.togglePause();

			break;
```

The same should be done in HeartBeat.js:
```
	// Event functions
	function KeyEvent(key) {
		switch (key) {
		case 114: // Pause/Break - we use F3 instead
			if (me.ingame) {
				break;
			}

			togglePause();

			break;
		}
	}
```

However, it is important to use the "Home" button always since otherwise both functions are triggered (seems to be a bug IMHO but didn't want to check how to fix it since the workaround with "Home" works flawlessly and is easy to remember.

Edit: changed key to F3 instead of alt since this was only the first test.
