### ISSUE TITLE
Rusher Question

### ISSUE THREAD

**Issue by tuito1** [kolton/d2bot-with-kolbot#881]
Hey everyone, I got a quick question about rusher scrypt, I am trying to rush

How do I make my rusher join the same game of my rushee?, because my rusher just try to make a new game

I all ready set the leader's name of the rusher on my rushee scrypt

**Comment by cameronpfs** [comment]
since it is a rusher you could use entry script botblank and manually place them in a game, seeing as its only a 10 minute run max, or probably what you are asking should be setup like this:
Rushee uses d2botLead with game name etc set
Rusher uses D2botFollow with (Rushee's profile name set as variable)

Although I prefer the simple manual entry to the game seeing as its just easier than to change all those parameters for something that takes 2 seconds.
