### ISSUE TITLE
stop bot when cant res merc

### ISSUE THREAD

**Issue by mixxer4** [kolton/d2bot-with-kolbot#907]
i dont know how my toon runs out of gold, but my sorc does and cant res her merc, and will die/chicken pretty much anywhere without him. i know theres a line of script to res merc if you dont have him, but i need something to stop all the scripts from running the bot if the merc cannot be revived, if thats possible

**Comment by DarkHorseDre** [comment]
I'm not sure of the command to pause the profile and cant check properly from work, but you want to turn mercwatch on so toon returns to town to revive immediately (not at end of run).

line 1460 of `town.js`
// "You do not have enough gold for that."
                if (dialog[lines].text.match(getLocaleString(3362), "gi")) {
                    return false;
                }
so I'm thinking you want a quit line instead of the return false, 

I've seen these two entries in townchicken but not sure which is correct, if any:
`script.pause();`
`scriptBroadcast("quit");`

Give it a try in the meantime.  Maybe one of the knowledgeable ones will answer soon!

**Comment by wojte5379** [comment]
hi btw , if merc dies, for example, on Sanctuary. Where it needs to be changed in code to returns to the city and rent him again ?

**Comment by DarkHorseDre** [comment]
You just need to set in character config file:

if this is set, it will hire and rehire merc when in town.
`Config.UseMerc = true; // Use merc. This is ignored and always false in d2classic.`

if this is set, it will rehire as soon as he dies:
`Config.MercWatch = true; // Instant merc revive during battle.`
